### ISSUE TITLE
Switch on Sherpa pyextension (For UFO model support)

### ISSUE THREAD

**Issue by thuer** [cms-sw/cmsdist#2341]
In Sherpa v2.2, UFO models are supported if Sherpa is compiled with the --pyext flag, which is currently not set. If add this flag to the Sherpa external, serveral issues occur. To build Sherpa with this flag two externals are needed:

1) scons

2) swig

Both are present in cmsdist but not build by default. Once Sherpa is built with the --pyext executable, some additional changes are needed:

1) scons executable has to be added to $PATH

2) Sherpa & py2-setuptools have to be added to $PYTHONPATH

On top of that, the Sherpa source code has to be adjusted due to the relocation of the package (Sherpa uses the hardcoded paths during compilation and we can switch them to environmental variables, see [1]). When using the new Sherpa executable with an UFO model a shared library is created (which is written to the Sherpa installation directory). Since this is not possible in a regular CMSSW installation, this needs to be changed. In [1] the path was changed to /tmp/test for testing. This is not an option for the final implementation. Maybe $PWD is an option?

[1] https://github.com/thuer/sherpa/commit/5e993a3cbf89946ba7397c5bc22d27b5146e7adb

**Comment by davidlange6** [comment]
in turn, swig depends on PCRE. 
scons doesn't seem like an issue.

for the paths and such - have we not already solved this issue for other sherpa components?

**Comment by thuer** [comment]
Yes, the pathes are defined in the sherpa toolfile and are used in the SherpaInterface and such. 
This new file in Sherpa (was included in the latest version) somehow uses again the pathes at compilation time and we have to change it to use the ones defined in the toolfile.
I will write the Sherpa authors to fix this in the next release.

**Comment by thuer** [comment]
The sherpa authors will change the hardcoded path variables and add an option to change the directory where the library is created in the next versions. So the Sherpa fix will only be temporary.
Still the issue with the externals need to be addressed.

**Comment by ghost** [comment]
@iahmad-khan Can you please take care of this one also?

**Comment by ghost** [comment]
@iahmad-khan ping?

**Comment by iahmad-khan** [comment]
@thuer can you please confirm that swig and scons are just build requires or run-time requires. i just read from the same sherpa documentation , from which i concluded that swig is build time require. but not sure about scons.

**Comment by thuer** [comment]
Scons is needed at run-time (e.g. the new executable makes explicit calls to scons https://github.com/thuer/sherpa/blob/cms/v2.2.0/MODEL/UFO/Sherpa-generate-model)
We sent an email to ask the authors regarding swig.

**Comment by pmillet** [comment]
The authors confirmed that swig is only needed for compilation, while scons is needed at runtime.

**Comment by iahmad-khan** [comment]
Thanks , i ll update the relevant spec files accordingly

**Comment by iahmad-khan** [comment]
@thuer @degano sherpa ,scons , and swig related changes fixed in  #2356

**Comment by iahmad-khan** [comment]
@thuer the new changes to sherpa are available in 8_1_X , can you please confirm the desired behavior.

**Comment by davidlt** [comment]
ping^1

**Comment by thuer** [comment]
thanks 
I'll start looking into it and testing it, sorry for the delay

**Comment by thuer** [comment]
Building Sherpa worked fine, however, I still cannot use the newly generated "Sherpa-generate-model" executable. 
The first error is related to py2-setuptools, while using the generate-model file, I encounter the error

ImportError: No module named pkg_resources

which I could fix by 
export PYTHONPATH=$PYTHONPATH:/cvmfs/cms-ib.cern.ch/2016-30/slc6_amd64_gcc493/external/py2-setuptools/2.1-giojec/lib/python2.7/site-packages

The second error is related to scons, the executable is not found in the environment, by manually adding the path to $PATH it worked fine. I assume the line 

```
<environment name="BINDIR" default="$SCONS_BASE/bin"/>
```

is not enough and we also need 

```
<runtime name="PATH" value="$BINDIR" type="path"/>
```

in the scons-toolfile.
Also I do not know how to test if everything works after relocation, I assume Sherpa has to be added to the PYTHONPATH as well.

**Comment by thuer** [comment]
When I try to build Sherpa in gcc530, for some reason cmsBuild also wants to build root and this fails with this error (I doubt this is in any way related to Sherpa, but just wanted to mention it)

> The action "install-lcg+root+6.06.04-cms" was not completed successfully because Traceback (most recent call last):
> File "/build/thuer/ext/CMSSW_8_1_X/20160718_1316/PKGTOOLS/scheduler.py", line 199, in doSerial
> result = commandSpec[0](*commandSpec[1:])
> File "PKGTOOLS/cmsBuild", line 2908, in installPackage
> File "PKGTOOLS/cmsBuild", line 2757, in installRpm
> RpmInstallFailed: Failed to install package root. Reason:
> error: Failed dependencies:
>         /bin/perl is needed by lcg+root+6.06.04-cms-1-1.x86_64 
> `

**Comment by smuzaffar** [comment]
@thuer , we will update the toolfile to have scons in PATH and py2-setuptools and sherpa dirs in PYTHONPATH.

For root errors, which branch of cmsdist/pkgtools you are using?

**Comment by thuer** [comment]
I used
pkgtools V00-24-XX
cmsdist IB/CMSSW_8_1_X/gcc530

**Comment by thuer** [comment]
Everything seems to be fine with the updates from 3 days ago to py2-setuptools, scons and the sherpa-toolfile. So we can close this issue and we will make a pull request with a new Sherpa release (2.2.1) which includes some fixes we requested on the Sherpa side
Can we ignore the root problem with gcc530?

**Comment by smuzaffar** [comment]
+externals
@thuer , can we close this issue now. This should be in 81X via
https://github.com/cms-sw/cmsdist/pull/2399

**Comment by smuzaffar** [comment]
assign externals

**Comment by thuer** [comment]
Thanks @smuzaffar @iahmad-khan for taking care of this!
Everything is fine from our point, so I'll close it

**Comment by smuzaffar** [comment]
@pmillet and @thuer , one workflow (in 81X IBs) 534.0  sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER is failing after this update. Can you please look in to it? 

```
https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc6_amd64_gcc530/CMSSW_8_1_X_2016-08-09-1100/pyRelValMatrixLogs/run/534.0_sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+HARVESTGEN/step1_sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+sherpa_ZtoEE_0j_OpenLoops_13TeV_MASTER+HARVESTGEN.log
```

**Comment by thuer** [comment]
@smuzaffar sorry forgot to update the RelVal samples to the new sherpa version
I made a pull request cmssw/pull/15416
