### ISSUE TITLE
Converters in lwtnn are not accessible (CMSSW 102X)

### ISSUE THREAD

**Issue by karavdin** [cms-sw/cmsdist#5122]
Converters in lwtnn external package are not accessible. For example attempt to run/open following script leads to "Permission denied":
/cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/lwtnn/2.4-gnimlf4/converters/keras2json.py

**Comment by kpedro88** [comment]
assign externals

**Comment by kpedro88** [comment]
It looks like the permissions on the files are set incorrectly:
```
[pedrok@cmslpc24 test]$ ls -lth /cvmfs/cms.cern.ch/slc6_amd64_gcc700/external/lwtnn/2.4-gnimlf4/converters/
total 42K
-r-x------ 1 cvmfs cvmfs 1.8K Aug 24  2017 agile2json.py
-r-x------ 1 cvmfs cvmfs 5.3K Aug 24  2017 julian2json.py
-r-x------ 1 cvmfs cvmfs 5.1K Aug 24  2017 keras2json.py
-r-x------ 1 cvmfs cvmfs  606 Aug 24  2017 keras_layer_converters_common.py
-r-x------ 1 cvmfs cvmfs 8.8K Aug 24  2017 keras_v1_layer_converters.py
-r-x------ 1 cvmfs cvmfs 5.0K Aug 24  2017 keras_v2_layer_converters.py
-r-x------ 1 cvmfs cvmfs  14K Aug 24  2017 kerasfunc2json.py
```

**Comment by davidlange6** [comment]
seems this is the fix

https://github.com/lwtnn/lwtnn/pull/84/files

we should just try updating lwtnn

**Comment by davidlange6** [comment]
https://github.com/cms-sw/cmsdist/pull/5125

**Comment by fabiocos** [comment]
@karavdin could you please confirm that the problem is solved in the latest IBs?

**Comment by fabiocos** [comment]
for the time being the 11_0_X IB...

**Comment by karavdin** [comment]
@fabiocos I can confirm that issue with access to converters is gone in CMSSW_11_0_DEVEL_X_2019-08-11-2300. Thank you for quick fix!
Would it be possible to propagate it to 10X, please?

**Comment by karavdin** [comment]
Quick update, although access to converters is possible, one still can't use it. At least keras2json.py script does not work properly, due to issue fixed in lwtnn master branch some time ago. I've just asked them to create new tag (https://github.com/lwtnn/lwtnn/issues/98), after this is done one more version update for this package will be needed.

**Comment by dguest** [comment]
@karavdin, I just created a new release (v2.10) hopefully that solves your issue.

**Comment by karavdin** [comment]
@fabiocos, @davidlange6, the issue with sequence conversion for from Keras 2.2 is fixed in lwtnn with tag v2.10. Can you upgrade the version in the external packages, please?

**Comment by smuzaffar** [comment]
https://github.com/cms-sw/cmsdist/pull/5194 updates lwtnn to v2.10

**Comment by karavdin** [comment]
Works in CMSSW_11_0_0_pre7
